<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UUTUU8G" ignored="0" name="Default test" tests="14" failures="1" timestamp="06 Sep 2019 10:24:03 GMT" time="59.492" errors="0">
  <testcase name="pageTitleVerify" time="4.138" classname="Practice_Section.WebCloudApplicationPage"/>
  <testcase name="pageTitleVerify" time="3.178" classname="Practice_Section.FAQPage"/>
  <testcase name="pageTitleVerify" time="5.044" classname="Practice_Section.TestimonialPage"/>
  <testcase name="pageTitleVerify" time="9.51" classname="Practice_Section.ClientsPage"/>
  <testcase name="pageTitleVerify" time="5.303" classname="Practice_Section.HowItWorksPage"/>
  <testcase name="pageTitleVerify" time="5.019" classname="Practice_Section.SoftwareDevPage"/>
  <testcase name="pageTitleVerify" time="4.194" classname="Practice_Section.ContactPage"/>
  <testcase name="pageTitleVerify" time="5.369" classname="Practice_Section.MobileAppDevPage"/>
  <testcase name="pageTitleVerify" time="3.519" classname="Practice_Section.SoftwareModernizationPage"/>
  <testcase name="pageTitleVerify" time="3.871" classname="Practice_Section.DevelopementTeamPage"/>
  <testcase name="pageTitleVerify" time="0.016" classname="Practice_Section.HomePage">
    <failure type="java.lang.AssertionError" message="expected [Hire Tech Experts For Your Software Projects - Tech.us] but found [Hire Tech.us For Your Dedicated Development Team - Tech.us]">
      <![CDATA[java.lang.AssertionError: expected [Hire Tech Experts For Your Software Projects - Tech.us] but found [Hire Tech.us For Your Dedicated Development Team - Tech.us]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Practice_Section.HomePage.pageTitleVerify(HomePage.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pageTitleVerify -->
  <testcase name="pageTitleVerify" time="3.126" classname="Practice_Section.PricingPage"/>
  <testcase name="pageTitleVerify" time="4.703" classname="Practice_Section.ArtificialInteligencePage"/>
  <testcase name="pageTitleVerify" time="2.329" classname="Practice_Section.OurServices"/>
</testsuite> <!-- Default test -->
